# Uncomment the next line to define a global platform for your project
 platform :ios, '10.0'

target 'WQKit' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for WQKit
  pod 'AFNetworking'
  pod 'CocoaLumberjack'
  pod 'FMDB'
  pod 'DZNEmptyDataSet'
  pod 'MJRefresh'
  pod 'FLAnimatedImage'
  pod 'iCarousel'
  pod 'Masonry'
  pod 'MBProgressHUD'
  pod 'SDWebImage'
  pod 'KVOController'
  pod 'YYKit'
  pod 'DeviceUtil'
  pod 'TTTAttributedLabel'
  pod 'AMap3DMap-NO-IDFA'
end

